- include_vars: empire.yml
- shell: /usr/sbin/make_dockercfg {{docker_user|quote}} {{docker_pass|quote}} {{docker_email|quote}} {{docker_registry|quote}} > /etc/empire/dockercfg
  args:
    creates: /etc/empire/dockercfg
- copy: src=etc/init/empire.conf dest=/etc/init/empire.conf
  notify: 
    - restart_empire
- template: src=etc/empire/env/empire.env dest=/etc/empire/env/empire.env mode=0640 owner=root group=root
  notify: 
    - restart_empire

- service: name=empire state=started
